name: Deployment Workflow
on:
  push:
    branches: [main]
  
jobs:
  first_job:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: calliar.arbml.org
        username: arabicmachinelearning
        key: ${{ secrets.SECRET_SSHKEY }}
        port: 22
        script: |
          cd ~
          rm -rf atmatah
          git clone git@github.com:ARBML/atmatah.git
          cd atmatah
          python3 -m venv venv
          venv/bin/python -m pip install requirements.txt
          echo {{ $secrets.ANS_PASS }} > .config/ansible_pass.password
          ansible-playbook -i environment/inventory app.yml --vault-password-file=.config/ansible_pass.password
          cd ..
          rm -rf atmatah
    