name: Deployment Workflow
on:
  push:
    branches: [main]
  
jobs:
  first_job:
    name: Deploy Calliar Website
    runs-on: ubuntu-latest
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: calliar.arbml.org
        username: arabicmachinelearning
        key: ${{ secrets.SECRET_SSHKEY }}
        port: 22
        script: |
          cd ~
          rm -rf atmatah
          echo cloning atmatah repo
          git clone https://github.com/ARBML/atmatah.git
          cd atmatah
          echo creating venv and install requirements
          python3 -m venv venv
          venv/bin/python -m pip install -r requirements.txt
          venv/bin/ansible-galaxy install -r requirements.yml
          echo prepare for deploy
          mkdir .config
          echo {{ $secrets.ANS_PASS }} > .config/ansible_pass.password
          echo deploy calliar app
          venv/bin/ansible-playbook -i apps/calliar/inventory apps/calliar/app.yml --vault-password-file=.config/ansible_pass.password --connection=local
          echo cleanup
          cd ..
          rm -rf atmatah
    